# Generated by Django 5.2.8 on 2025-12-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='return_date',
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='days_required',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
