# Generated by Django 5.2.8 on 2025-12-21 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_borrowrequest_borrow_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
