# Generated by Django 5.2.8 on 2025-12-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_borrowrequest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='extended_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='extra_fine',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
