# Generated by Django 6.0 on 2025-12-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_borrowrequest_extended_days_borrowrequest_extra_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='extension_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='extension_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10),
        ),
    ]
