# Generated by Django 6.0 on 2026-01-02 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_order_book_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
