# Generated by Django 5.2.8 on 2026-01-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_borrowrequest_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
